import ThemeProvider from '@/providers/ThemeProvider'
import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

const roboto = Roboto({weight: ["100", "300", "400", "500", "700", "900"], subsets: ["latin"] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  header,
  footer,

}: {
  children: React.ReactNode,
  header: React.ReactNode,
  footer: React.ReactNode,
}) {
  return (
    <ThemeProvider>
      <html lang="ru">
        <body className={roboto.className}>
          {header}
          {children}
          {footer}
        </body>
      </html>
    </ThemeProvider>
  )
}
