import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

const roboto = Roboto({weight: ["100", "300", "400", "500", "700", "900"], subsets: ["latin"] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  footer
}: {
  children: React.ReactNode,
  footer: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={roboto.className}>
        {children}
        {footer}
      </body>
    </html>
  )
}
